### ISSUE TITLE
Suspension of suspend why?

### ISSUE THREAD

**Issue by jarrard** [caffeine-ng/caffeine-ng#91] opened 2021-12-08 01:39 UTC
I look in the battery and brightness section of kde and see this. Not sure why steam is randomly stopping suspend, but why is libcaffeine always in this list? broken?

![Y1208_120727](https://user-images.githubusercontent.com/17428910/145133013-baecdd29-0e32-40a0-a2aa-bf64b04ce359.jpeg)

**Comment by WhyNotHugo** [comment] 2021-12-08 16:05
Duplicate of #78

**Closed by WhyNotHugo** 2021-12-08 16:05 UTC
